[shell]
corner_radius_scale = 0.0
polkit_agent = true
popup_shadows = false

    [shell.panel]
    shadow = false
    transparency_mode = "soft"

[lockscreen]
blurred_desktop = true

[osd]
background_opacity = 0.79999998211860657
position = "bottom_center"

[theme]
custom_palette = "skwdwall"
mode = "dark"
source = "custom"

[wallpaper]
enabled = false
